name: innoday-dagger

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DAGGER_CACHE_FROM: type=gha,scope=dagger-cache
      DAGGER_CACHE_TO: type=gha,mode=max,scope=dagger-cache
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Dagger project update
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: project update

      - name: Dagger test
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: do test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    env:
      DAGGER_CACHE_FROM: type=gha,scope=dagger-cache
      DAGGER_CACHE_TO: type=gha,mode=max,scope=dagger-cache
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Dagger project update
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: project update

      - name: Dagger push to Docker
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: do push
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
