name: innoday-dagger

on:
  push:
    branches:
      - main

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Dagger project update
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: project update

      - name: Dagger test
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: do test

      - name: Dagger push to Docker
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: do push
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
